# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timet', '0003_auto_20171102_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_final',
            name='teaching_hours',
            field=models.SmallIntegerField(default=0),
        ),
    ]
