# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timet', '0005_auto_20171106_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_final',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
        ),
    ]
