# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Section', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Department')),
            ],
        ),
        migrations.AddField(
            model_name='sec',
            name='sem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semclass.Sem'),
        ),
    ]
