# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semclass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sem',
            name='sem',
            field=models.SmallIntegerField(),
        ),
    ]
