# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-30 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semclass', '0002_auto_20171030_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='sec',
            name='complete',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
