# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-30 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semclass', '0003_sec_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sec',
            name='complete',
        ),
    ]
