# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semclass', '0002_auto_20171030_1252'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='sec',
        ),
        migrations.AddField(
            model_name='classroom',
            name='sec1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sec1', to='semclass.Sec'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='sec2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sec2', to='semclass.Sec'),
        ),
    ]
