# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20171030_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='added_on',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='status',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='added_on',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='status',
        ),
        migrations.AddField(
            model_name='lab',
            name='sec',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
