# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-01 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20171102_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='shift',
            field=models.SmallIntegerField(choices=[(0, 'I'), (1, 'II')], default=0),
        ),
    ]
